services:

     fdp:
         image: fairdata/fairdatapoint:latest
         volumes:
             - ./application.yml:/fdp/application.yml:ro

     fdp-client:
         image: fairdata/fairdatapoint-client:latest
         ports:
             - 8085:80
         environment:
             - FDP_HOST=fdp

     mongo:
         image: mongo:4.0.12
         ports:
             - 27017:27017
         volumes:
             - ./mongo/data:/data/db
    
     graphdb:
         image: ontotext/graphdb:10.7.4
         ports:
             - 7200:7200
         volumes:
             - ./graphdb/data:/data